<form class="formAddSeries text-center p-5" method="POST" action="page_form_add_series.php">

    <p class="h2 mb-5 formAddSeriesText"><u><b>Ajouter une série!</u></b></p>

    <label for="addSeriesTitle">Titre de la série</label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesTitle']) ? $errorMessageAddSeries['addSeriesTitle'] : ''; ?></span><input type="text" id="addSeriesTitle" class="form-control mb-4" name="addSeriesTitle" value="<?= isset($_POST['addSeriesTitle']) ? $_POST['addSeriesTitle'] : ''; ?>" />
    <label for="addSeriesDescription">Description de la série</label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesDescription']) ? $errorMessageAddSeries['addSeriesDescription'] : ''; ?></span><textarea id="addSeriesDescription" class="form-control mb-4" name="addSeriesDescription" value="<?= isset($_POST['addSeriesDescription']) ? $_POST['addSeriesDescription'] : ''; ?>" /></textarea>
<label for="addSeriesSeasonsNumber">Nombre de saisons</label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesSeasonsNumber']) ? $errorMessageAddSeries['addSeriesSeasonsNumber'] : ''; ?></span><input type="number" id="addSeriesSeasonsNumber" min="1" class="form-control mb-4" name="addSeriesSeasonsNumber" value="<?= isset($_POST['addSeriesSeasonsNumber']) ? $_POST['addSeriesSeasonsNumber'] : ''; ?>"/>
<label for="addSeriesEpisodesNumber">Nombre d'épisodes</label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesEpisodesNumber']) ? $errorMessageAddSeries['addSeriesEpisodesNumber'] : ''; ?></span><input type="number" id="addSeriesEpisodesNumber" min="1" class="form-control mb-4" name="addSeriesEpisodesNumber" value="<?= isset($_POST['addSeriesEpisodesNumber']) ? $_POST['addSeriesEpisodesNumber'] : ''; ?>"/>
<label for="addSeriesEpisodesDuration">Durée d'un épisode</label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesEpisodesDuration']) ? $errorMessageAddSeries['addSeriesEpisodesDuration'] : ''; ?></span><input type="number" id="addSeriesEpisodesDuration" min="1" class="form-control mb-4" name="addSeriesEpisodesDuration" value="<?= isset($_POST['addSeriesEpisodesDuration']) ? $_POST['addSeriesEpisodesDuration'] : ''; ?>"/>
<label for="addSeriesDiffusion">Chaîne de diffusion</label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesDiffusion']) ? $errorMessageAddSeries['addSeriesDiffusion'] : ''; ?></span><input type="text" id="addSeriesDiffusion" class="form-control mb-4" name="addSeriesDiffusion" value="<?= isset($_POST['addSeriesDiffusion']) ? $_POST['addSeriesDiffusion'] : ''; ?>"/>
<button class="spStyleButton btn btn-block text-white my-4" type="submit" id="add_series_button">Valider</button>
</form>