<form class="formAddSeries text-center p-5" method="POST" action="page_form_add_series.php">

    <p class="h2 mb-5 formAddSeriesText"><u><b>Ajouter une série!</u></b></p>

    <label for="addSeriesTitle"><b>Titre de la série <i class="fas fa-pen ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesTitle']) ? $errorMessageAddSeries['addSeriesTitle'] : ''; ?></span><input type="text" id="addSeriesTitle" class="form-control mb-4" name="addSeriesTitle" value="<?= isset($_POST['addSeriesTitle']) ? $_POST['addSeriesTitle'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Titre de la série" data-content="Merci d'ajouter le titre de la série. Vérifie bien les majuscules."  required />

    <label for="addSeriesDescription"><b>Description de la série <i class="fas fa-book-open ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesDescription']) ? $errorMessageAddSeries['addSeriesDescription'] : ''; ?></span><textarea id="addSeriesDescription" class="form-control mb-4" name="addSeriesDescription" value="<?= isset($_POST['addSeriesDescription']) ? $_POST['addSeriesDescription'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Description de la série" data-content="Merci d'ajouter la description de la série. Recherche la description officielle sur le net et copie la ici."  required ></textarea>

    <label for="addSeriesSeasonsNumber"><b>Nombre de saisons <i class="fas fa-sort-numeric-up ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesSeasonsNumber']) ? $errorMessageAddSeries['addSeriesSeasonsNumber'] : ''; ?></span><input type="number" id="addSeriesSeasonsNumber" min="1" class="form-control mb-4" name="addSeriesSeasonsNumber" value="<?= isset($_POST['addSeriesSeasonsNumber']) ? $_POST['addSeriesSeasonsNumber'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Nombre de saison de la série" data-content="Merci d'ajouter le nombre de saison de la série. Toutes les informations ce trouvent sur Wikipedia." required />

    <label for="addSeriesEpisodesNumber"><b>Nombre d'épisodes <i class="fas fa-sort-numeric-up ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesEpisodesNumber']) ? $errorMessageAddSeries['addSeriesEpisodesNumber'] : ''; ?></span><input type="number" id="addSeriesEpisodesNumber" min="1" class="form-control mb-4" name="addSeriesEpisodesNumber" value="<?= isset($_POST['addSeriesEpisodesNumber']) ? $_POST['addSeriesEpisodesNumber'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Nombre d'épisode de la série" data-content="Merci d'ajouter le nombre d'épisode de la série. Toutes les informations ce trouvent sur Wikipedia." required />

    <label for="addSeriesEpisodesDuration"><b>Durée d'un épisode <i class="far fa-clock ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesEpisodesDuration']) ? $errorMessageAddSeries['addSeriesEpisodesDuration'] : ''; ?></span><input type="number" id="addSeriesEpisodesDuration" min="1" class="form-control mb-4" name="addSeriesEpisodesDuration" value="<?= isset($_POST['addSeriesEpisodesDuration']) ? $_POST['addSeriesEpisodesDuration'] : ''; ?>"  data-toggle="popover" data-trigger="focus" title="Durée moyenne d'un épisode" data-content="Merci d'ajouter la durée moyenne d'un épisode. Toutes les informations ce trouvent sur Wikipedia." required />

    <label for="addSeriesDiffusion"><b>Chaîne de diffusion <i class="fas fa-tv ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesDiffusion']) ? $errorMessageAddSeries['addSeriesDiffusion'] : ''; ?></span><input type="text" id="addSeriesDiffusion" class="form-control mb-4" name="addSeriesDiffusion" value="<?= isset($_POST['addSeriesDiffusion']) ? $_POST['addSeriesDiffusion'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Chaîne de diffusion de la série" data-content="Merci d'ajouter la chaîne de diffusion de la série. Toutes les informations ce trouvent sur Wikipedia." required />

    <label for="addSeriesTrailer"><b>Trailer <i class="fab fa-youtube ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesTrailer']) ? $errorMessageAddSeries['addSeriesTrailer'] : ''; ?></span><input type="text" id="addSeriesTrailer" class="form-control mb-4" name="addSeriesTrailer" value="<?= isset($_POST['addSeriesTrailer']) ? $_POST['addSeriesTrailer'] : ''; ?>"  data-toggle="popover" data-trigger="focus" title="Trailer de la série" data-content="Merci d'ajouter le trailer de la série. Le trailer ce trouve sur YouTube, il suffit de remplacer 'watch?v=' par 'embed/'." required />

    <label for="addSeriesImage"><b>Image de la série <i class="far fa-image ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesImage']) ? $errorMessageAddSeries['addSeriesImage'] : ''; ?></span><input type="text" id="addSeriesImage" class="form-control mb-4" name="addSeriesImage" value="<?= isset($_POST['addSeriesImage']) ? $_POST['addSeriesImage'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Image de la série" data-content="Merci d'ajouter l'image de la série. Rentrer le nom de l'image. Exemple : nomdelimage.jpg" required />

    <label for="addSeriesFrenchTitle"><b>Titre français <i class="fas fa-flag ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesFrenchTitle']) ? $errorMessageAddSeries['addSeriesFrenchTitle'] : ''; ?></span><input type="text" id="addSeriesFrenchTitle" class="form-control mb-4" name="addSeriesFrenchTitle" value="<?= isset($_POST['addSeriesFrenchTitle']) ? $_POST['addSeriesFrenchTitle'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Titre français de la série" data-content="Merci d'ajouter le titre français de la série. Toutes les informations ce trouvent sur Wikipedia." required />

    <label for="addSeriesOriginalTitle"><b>Titre original <i class="far fa-flag ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesOriginalTitle']) ? $errorMessageAddSeries['addSeriesOriginalTitle'] : ''; ?></span><input type="text" id="addSeriesOriginalTitle" class="form-control mb-4" name="addSeriesOriginalTitle" value="<?= isset($_POST['addSeriesOriginalTitle']) ? $_POST['addSeriesOriginalTitle'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Titre original de la série" data-content="Merci d'ajouter le titre original de la série. Toutes les informations ce trouvent sur Wikipedia." required />

    <label for="addSeriesOrigin"><b>Origine de la série <i class="fas fa-globe-europe ml-2"></i></b></label><span class="errorMessage d-block text-danger"><?= isset($errorMessageAddSeries['addSeriesOrigin']) ? $errorMessageAddSeries['addSeriesOrigin'] : ''; ?></span><input type="text" id="addSeriesOrigin" class="form-control mb-4" name="addSeriesOrigin" value="<?= isset($_POST['addSeriesOrigin']) ? $_POST['addSeriesOrigin'] : ''; ?>" data-toggle="popover" data-trigger="focus" title="Origine de la série" data-content="Merci d'ajouter l'origine de la série. Toutes les informations ce trouvent sur Wikipedia." required />

    <button class="spStyleButton btn btn-block text-white my-4" type="submit" id="add_series_button">Valider</button>
</form>