INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''hiver vient', '1.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Route royale', '1.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Lord Snow', '1.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Infirmes, Bâtards et Choses brisées', '1.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Loup et le Lion', '1.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Une couronne dorée', '1.6', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Gagner ou mourir', '1.7', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Frapper d''estoc', '1.8', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Baelor', '1.9', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('De feu et de sang', '1.10', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Nord se souvient', '2.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Contrées nocturnes', '2.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Ce qui est mort ne saurait mourir', '2.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Jardin des os', '2.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Fantôme d''Harrenhal', '2.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Anciens et les Nouveaux Dieux', '2.6', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Un homme sans honneur', '2.7', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Prince de Winterfell', '2.8', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Néra', '2.9', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Valar Morghulis', '2.10', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Valar Dohaeris', '3.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Noires Ailes, Noires Nouvelles', '3.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Immaculés', '3.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Voici que son tour de garde est fini', '3.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Baisée par le feu', '3.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Ascension', '3.6', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Ours et la Belle', '3.7', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Puînés', '3.8', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Pluies de Castamere', '3.9', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Mhysa', '3.10', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Deux épées', '4.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Lion et la Rose', '4.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Briseuse de chaînes', '4.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Féale', '4.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Premier du nom', '4.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Lois des dieux et des hommes', '4.6', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Oiseau moqueur', '4.7', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Montagne et la Vipère', '4.8', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Veilleurs au rempart', '4.9', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Enfants', '4.10', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Guerres à venir', '5.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Demeure du noir et du blanc', '5.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Grand Moineau', '5.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Fils de la Harpie', '5.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Tue l''enfant', '5.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Insoumis, Invaincus, Intacts', '5.6', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Cadeau', '5.7', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Durlieu', '5.8', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Une danse avec les dragons', '5.9', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Miséricorde de la Mère', '5.10', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Femme rouge', '6.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Maison', '6.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Briseur de serments', '6.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Livre de l''Étranger', '6.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Porte', '6.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('De mon sang', '6.6', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Homme brisé', '6.7', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Personne', '6.8', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Bataille des bâtards', '6.9', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Vents de l''hiver', '6.10', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Peyredragon', '7.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Née du Typhon', '7.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Justice de la reine', '7.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Butins de guerre', '7.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Fort-Levant', '7.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Au-delà du Mur', '7.6', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Dragon et le Loup', '7.7', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Winterfell', '8.1', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Un chevalier des Sept Couronnes', '8.2', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Longue Nuit', '8.3', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Derniers des Stark', '8.4', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Cloches', '8.5', '5');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Trône de fer', '8.6', '5');