INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 1', '1.1', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 2', '1.2', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 3', '1.3', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 4', '1.4', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 5', '1.5', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 6', '1.6', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 1', '2.1', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 2', '2.2', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 3', '2.3', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 4', '2.4', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 5', '2.5', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 6', '2.6', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 1', '3.1', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 2', '3.2', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 3', '3.3', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 4', '3.4', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 5', '3.5', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Épisode 6', '3.6', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La corde au cou', '4.1', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Sauvages', '4.2', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Blackbird', '4.3', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Dangereuse', '4.4', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le duel', '4.5', '11');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La société', '4.6', '11');