INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Une étude en rose ', '1.1', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Banquier aveugle', '1.2', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Grand Jeu', '1.3', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Un scandale à Buckingham', '2.1', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Chiens de Baskerville', '2.2', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Chute du Reichenbach', '2.3', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Cercueil vide', '3.1', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Signe des trois', '3.2', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Son dernier coup d''éclat', '3.3', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Six Thatcher', '4.1', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Détective affabulant', '4.2', '44');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Dernier Problème', '4.3', '44');