INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Morsure', '1.1', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Transformation incontrôlée', '1.2', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Appel de la meute', '1.3', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('48 heures', '1.4', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Puma', '1.5', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Pulsations', '1.6', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Une nuit au lycée', '1.7', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Emprise de la Lune', '1.8', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Alpha', '1.9', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Esprit d''équipe', '1.10', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Bal', '1.11', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Code d''honneur', '1.12', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Omega', '2.1', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La chasse est ouverte', '2.2', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Question de pouvoir', '2.3', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Abomination', '2.4', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Meute contre Meute', '2.5', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Art de la guerre', '2.6', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Sous contrôle', '2.7', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Imagination et le Savoir', '2.8', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Anniversaire de Lydia', '2.9', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Furie', '2.10', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Champ de bataille', '2.11', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Immortels', '2.12', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Plaies ouvertes', '3.1', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Risque et la Récompense', '3.2', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Chasse', '3.3', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Prédateur', '3.4', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Tensions', '3.5', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Motel California', '3.6', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Guérisseurs', '3.7', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Œil pour œil', '3.8', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Fille qui en savait trop', '3.9', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Laissés pour compte', '3.10', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Nemeton', '3.11', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Éclipse lunaire', '3.12', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Ancrage', '3.13', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Malia', '3.14', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Musca', '3.15', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Marque', '3.16', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Doigt d''argent', '3.17', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''Énigme', '3.18', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Poison', '3.19', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Eichen House', '3.20', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Renard et le loup', '3.21', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Dans la tête de Stiles', '3.22', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Insatiable', '3.23', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Coup divin', '3.24', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Lune sombre', '4.1', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('117', '4.2', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Sourd', '4.3', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Bienfaiteur', '4.4', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Liam', '4.5', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Orphelins', '4.6', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Bien armé', '4.7', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('L''heure est venue', '4.8', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Périssable', '4.9', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Monstres', '4.10', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Promesse pour la mort', '4.11', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Fumée et Miroirs', '4.12', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Créatures de la nuit', '5.1', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Terreurs nocturnes', '5.2', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('En plein rêve', '5.3', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Phase terminale', '5.4', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Tout un roman', '5.5', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Livre de la mort', '5.6', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Mauvaises Fréquences', '5.7', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Ouroboros', '5.8', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Mensonges par omission', '5.9', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Asthme sévère', '5.10', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Dernière Chimère', '5.11', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Damnatio Memoriae', '5.12', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Codominance', '5.13', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Sabre et l''Esprit', '5.14', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Pouvoirs sans limite', '5.15', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('D''une meute à l''autre', '5.16', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Menace imminente', '5.17', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Servante du Gévaudan', '5.18', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Bête de Beacon Hills', '5.19', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Apothéose', '5.20', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Souvenir perdu', '6.1', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Superposition', '6.2', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Crépuscule', '6.3', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Reliques', '6.4', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Silence radio', '6.5', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Ville fantôme', '6.6', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Sans cœur', '6.7', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Guerre éclair', '6.8', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Souviens-toi', '6.9', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('La Dernière Chevauchée', '6.10', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Roi des rats', '6.11', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Talent brut', '6.12', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Images fantômes', '6.13', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Sans visage', '6.14', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Bras de fer', '6.15', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Le Déclencheur', '6.16', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Les Loups-garous de Londres', '6.17', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Génotype', '6.18', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Nuit de cristal', '6.19', '47');
INSERT INTO `sp_episodes_infos` (`sp_episodes_infos_name`, `sp_episodes_infos_number`, `id_sp_series_pages`) VALUES ('Carnage !', '6.20', '47');