-- 1 : 13 REASONS WHY

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('13 Reasons Why', 'Un garçon nommé Clay reçoit une boîte à chaussures remplies de cassettes de la part d''une de ses amies, Hannah Baker, récemment suicidée. Sur les cassettes qui doivent être passées de mains en mains, Hannah explique que chacun a joué un rôle dans sa mort, et donne les 13 raisons expliquant son passage à l''acte.', '2', '26', '55', 'Neflix', 'https://www.youtube.com/embed/LVVMvRpmu0s', '13ReasonsWhy.jpg', '13 Reasons Why', '13 Reasons Why', 'Amerique', '1');

-- 2 : SUPERNATURAL

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Supernatural', 'Les aventures et le destin des deux frères Winchester sur les traces de leur père, un "chasseur", à la poursuite de monstres vivant parmi les humains.', '14', '307', '40', 'The CW', 'https://www.youtube.com/embed/t-775JyzDTk', 'supernatural.jpg', 'Supernatural', 'Supernatural', 'Amerique', '1');

-- 3 : THE FLASH

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Flash', 'Barry Allen est un jeune scientifique qui travaille pour la police de Central City. Témoin enfant du meurtre de sa mère par une entité mystérieuse, il croit aux phénomènes paranormaux et cherche le moyen de le prouver pour faire innocenter son père emprisonné. Touché par un éclair provoqué par l''explosion de l''accélérateur de particules dans les laboratoires de Harrison Wells, Barry va sombrer dans le coma pendant neuf mois. À son réveil, il découvre qu''il peut courir à une vitesse surhumaine et peut guérir de façon accélérée. Il va réaliser par la suite qu''il n''est pas le seul à avoir obtenu des facultés extraordinaires et surhumaines.', '5', '113', '40', 'The CW', 'https://www.youtube.com/embed/Yj0l7iGKh8g', 'theFlash.jpg', 'The Flash', 'The Flash', 'Amerique', '1');

--  4 : BREAKING BAD 

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Breaking Bad', 'La vie de Walter White, professeur de chimie dans un lycée, est bouleversée lorsqu''il apprend qu''il est atteint d''un cancer en phase terminale. Une nouvelle qui le sort de la torpeur de son quotidien et l''amène à prendre des mesures radicales pour anticiper l''avenir de sa famille.', '5', '62', '45', 'AMC', 'https://www.youtube.com/embed/HhesaQXLuRY', 'breakingBad.jpg', 'Breaking Bad', 'Breaking Bad', 'Amerique', '1');

-- 5 : GAME OF THRONES

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Game Of Thrones', 'Il y a très longtemps, à une époque oubliée, une force a détruit l''équilibre des saisons. Dans un pays où l''été peut durer plusieurs années et l''hiver toute une vie, des forces sinistres et surnaturelles se pressent aux portes du Royaume des Sept Couronnes. La confrérie de la Garde de Nuit, protégeant le Royaume de toute créature pouvant provenir d''au-delà du Mur protecteur, n''a plus les ressources nécessaires pour assurer la sécurité de tous. Après un été de dix années, un hiver rigoureux s''abat sur le Royaume avec la promesse d''un avenir des plus sombres. Pendant ce temps, complots et rivalités se jouent sur le continent pour s''emparer du Trône de Fer, le symbole du pouvoir absolu.', '8', '73', '45', 'HBO', 'https://www.youtube.com/embed/gcTkNV5Vg1E', 'gameOfThrones.jpg', 'Game of Thrones', 'Game of Thrones', 'Amerique', '1');

-- 6 : LUCIFER

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Lucifer', 'Lassé et fatigué d''être le Seigneur des Enfers, Lucifer Morningstar abandonne son royaume et s''en va à Los Angeles où il est propriétaire d''une boîte de nuit appelée Lux. Lucifer a reçu le don de contraindre les gens à révéler leurs désirs les plus profonds. Un soir, Lucifer assiste au meurtre d''une chanteuse pop devant son club. Il décide donc d''aller à la recherche du coupable et croise sur son chemin une policière nommée Chloe Decker qui résiste à son don et lui met des bâtons dans les roues. Pendant que Lucifer Morningstar et Chloe Decker font équipe pour trouver le meurtrier, Dieu envoie l''ange Amenadiel sur Terre pour convaincre Lucifer de régner à nouveau sur l''Enfer.', '4', '67', '42', 'Netflix', 'https://www.youtube.com/embed/X4bF_quwNtw', 'lucifer.jpg', 'Lucifer', 'Lucifer', 'Amerique', '1');

-- 7 : THE WALKING DEAD

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Walking Dead', 'Le policier Rick Grimes se réveille à l''hôpital après un long coma. Il découvre avec effarement que le monde, ravagé par une épidémie, est envahi par les morts-vivants. Parti sur les traces de sa femme et de son fils, Rick arrive à Atlanta où, avec un groupe de rescapés, il va devoir apprendre à survivre.', '9', '131', '45', 'AMC', 'https://www.youtube.com/embed/sfAc2U20uyg', 'theWalkingDead.jpg', 'The Walking Dead', 'The Walking Dead', 'Amerique', '1');

-- 8 : THE BIG BANG THEORY

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Big Bang Theory', 'Que se passe-t-il quand les très intelligents colocataires Sheldon et Leonard rencontrent Penny, une beauté libre d''esprit qui emménage la porte d''à côté, et réalisent qu''ils ne connaissent presque rien de la vie hors de leur laboratoire. Leur bande d''amis est complétée par le mielleux Wolowitz, qui pense être aussi sexy que futé, et Koothrappali, qui est incapable de parler en présence de femmes.', '12', '279', '20', 'CBS', 'https://www.youtube.com/embed/3g2yTcg1QFI', 'theBigBangTheory.jpg', 'The Big Bang Theory', 'The Big Bang Theory', 'Amerique', '1');

-- 9 : BLACKLIST

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Blacklist', 'Raymond Red Reddington, l''un des fugitifs les plus recherchés par le FBI, se rend en personne au quartier général du FBI à Washington. Il affirme avoir les mêmes intérêts que le FBI : faire tomber des criminels dangereux et des terroristes. Au cours des deux dernières décennies, il a dressé une liste des criminels et terroristes qu''il croit introuvables par le FBI car ce dernier ne connaît même pas leurs existences. Reddington l''appelle La Liste noire ( The Blacklist ). Reddington coopérera, mais insiste pour ne parler qu''à Elizabeth Keen, une profileuse inexpérimentée du FBI, qui s''interroge sur l''intérêt soudain que Reddington lui porte, alors qu''il soutient qu''elle se trouve être très spéciale...', '6', '133', '43', 'NBC', 'https://www.youtube.com/embed/XihA6GWIBdM', 'blacklist.jpg', 'Blacklist', 'Blacklist', 'Amerique', '1');

-- 10 : THE 100

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The 100', 'Après une apocalypse causée par l''Homme lors d''une troisième Guerre Mondiale, les 318 survivants recensés se réfugient dans des stations spatiales et parviennent à y vivre et à se reproduire, atteignant le nombre de 4000. Mais 97 ans plus tard, le vaisseau mère, The Ark, est en piteux état. Une centaine de jeunes délinquants emprisonnés au fil des années pour des crimes ou des trahisons sont choisis comme cobayes par les autorités pour redescendre sur Terre et tester les chances de survie. Dès leur arrivée, ils découvrent un nouveau monde dangereux mais fascinant...', '6', '78', '42', 'The CW', 'https://www.youtube.com/embed/ia1Fbg96vL0', 'the100.jpg', 'The 100', 'The 100', 'Amerique', '1');

-- 11 : PEAKY BLINDERS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Peaky Blinders', 'À Birmingham, en Angleterre, l''année 1919 est marquée par les exactions de l''impitoyable Tommy Shelby, un jeune chef de la pègre ivre de son désir de domination.', '5', '24', '55', 'BBC', 'https://www.youtube.com/embed/oVzVdvGIC7U', 'peakyBlinders.jpg', 'Peaky Blinders', 'Peaky Blinders', 'Anglais', '1');

-- 12 : GREY'S ANATOMY

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Grey''s Anatomy', 'Meredith Grey, fille d''un chirurgien très réputé, commence son internat de première année en médecine chirurgicale dans un hôpital de Seattle. La jeune femme s''efforce de maintenir de bonnes relations avec ses camarades internes, mais dans ce métier difficile la compétition fait rage.', '15', '342', '40', 'ABC', 'https://www.youtube.com/embed/q1pcpgREQ5c', 'greysAnatomy.jpg', 'Grey''s Anatomy', 'Grey''s Anatomy', 'Amerique', '1');

-- 13 : SMALLVILLE

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Smallville', 'Dans une petite bourgade qui a connu une pluie de météorites quelques années plus tôt, le jeune Clark Kent est élevé par une famille de fermiers. Contraint de cacher ses pouvoirs exceptionnels, il va apprendre à les utiliser pour aller au secours de son prochain.', '10', '218', '40', 'The CW', 'https://www.youtube.com/embed/DAeLfedg_os', 'smallville.jpg', 'Smallville', 'Smallville', 'Amerique', '1');

-- 14 : THE VAMPIRE DIARIES

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Vampire Diaries', 'Elena Gilbert est une adolescente de 17 ans demeurant dans la mystérieuse ville de Mystic Falls en Virginie. Elle et son frère, Jeremy, 15 ans, vivent avec leur tante Jenna Sommers, depuis la mort de leurs parents, décédés dans un accident de voiture quatre mois auparavant. Elena trouve du réconfort dans son journal intime et avec ses deux meilleures amies, Bonnie Bennett et Caroline Forbes. Lors de la rentrée scolaire, elle croise Stefan Salvatore, un nouvel arrivant mystérieux, dont elle tombe immédiatement sous le charme avant de rencontrer son frère aîné diabolique, Damon Salvatore. Elle ne tarde pas à découvrir leur secret : ce sont des vampires. Cette rencontre va complètement changer sa vie ainsi que celles de ses amis.', '8', '171', '40', 'The CW', 'https://www.youtube.com/embed/BmVmhjjkN4E', 'theVampireDiaries.jpg', 'The Vampire Diaries', 'The vampire Diaries', 'Amerique', '1');

-- 15 : THE ORIGINALS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Originals', 'Niklaus Mikaelson retourne à la Nouvelle-Orléans pour détrôner l''un de ses anciens protégés, Marcel, qui règne sur la ville qu''il a créée en son absence. Klaus est également surpris de voir que Marcel est toujours en vie alors qu''il le pensait mort lors de l''incendie en 1919 qui a brulé la ville entière. À son retour, Klaus s''aperçoit que beaucoup de choses ont changé : les sorcières n''ont plus le droit de pratiquer de la magie, les loups-garous ont été exclus de la ville et les vampires règnent à présent en maîtres. Il apprend également qu''un enfant a été conçu à la suite d''une aventure qu''il a eue avec Hayley Marshall, une louve-garou.', '5', '92', '40', 'The CW', 'https://www.youtube.com/embed/GXrDYboUnnw', 'theOriginals.jpg', 'The Originals', 'The Originals', 'Amerique', '1');

-- 16 : LES FRÈRES SCOTT

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Les frères Scott', 'Lucas et Nathan sont deux jeunes hommes qui ne semblent rien avoir en commun mais ils sont liés par un secret qu''ils partagent avec le même père... Nathan est la star de l''équipe de basket de son lycée et une figure locale. Lucas, son demi-frère, essaie de faire le bonheur de sa mère dont il est le fils unique. La vie de Lucas et de Nathan prend un nouveau sens lorsque Lucas se retrouve dans l''équipe de Nathan. Une compétition s''engage alors entre eux deux sur tous les plans...', '9', '187', '40', 'The CW', 'https://www.youtube.com/embed/RaXR4Vj4OP0', 'oneTreeHill.jpg', 'Les frères Scott', 'One Tree Hill', 'Amerique', '1');

-- 17 : ARROW

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Arrow', 'Les nouvelles aventures de Green Arrow/Oliver Queen, combattant ultra efficace issu de l''univers de DC Comics et surtout archer au talent fou, qui appartient notamment à la Justice League. Disparu en mer avec son père et sa petite amie, il est retrouvé vivant 5 ans plus tard sur une île près des côtes Chinoises. Mais il a changé : il est fort, courageux et déterminé à débarrasser Starling City de ses malfrats...', '7', '160', '42', 'The CW', 'https://www.youtube.com/embed/ofzPONG8hDU', 'arrow.jpg', 'Arrow', 'Arrow', 'Amerique', '1');

-- 18 : AMERICAN HORROR STORY

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('American Horror Story', 'A chaque saison, son histoire. American Horror Story nous embarque dans des récits à la fois poignants et cauchemardesques, mêlant la peur, le gore et le politiquement correct. De quoi vous confronter à vos plus grandes frayeurs !', '8', '94', '40', 'FX', 'https://www.youtube.com/embed/-9KZr2Vn7CQ', 'americanHorrorStory.jpg', 'American Horror Story', 'American Horror Story', 'Amerique','1');

-- 19 : BANSHEE

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Banshee', 'Tout juste sorti de prison, un voleur de haut rang (spécialiste des diamants) s''installe dans une petite ville de Pennsylvanie, dans le comté fictif de Banshee, où il se fait passer pour le nouveau shérif ayant repris les insignes du vrai qui vient d''être assassiné sous ses yeux. Personnage énigmatique et bagarreur fuyant les démons d''un passé tumultueux, Lucas Hood a bien l''intention de faire régner la loi dans cette ville située en plein territoire Amish, mais à sa manière....', '4', '38', '45', 'Cinemax', 'https://www.youtube.com/embed/VI7haj7HTCA', 'banshee.jpg', 'Banshee', 'Banshee', 'Amerique', '1');

-- 20 : BATES MOTEL

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Bates Motel', 'Après la mort de son mari, Norma Bates décide de refaire sa vie loin de l''Arizona, dans la petite ville de White Pine Bay dans l''Oregon. Elle emmène avec elle son fils Norman, âgé de 17 ans, avec qui elle partage une relation fusionnelle compliquée.', '5', '50', '45', 'A&E', 'https://www.youtube.com/embed/L4ABq1FuEmI', 'batesMotel.jpg', 'Bates Motel', 'Bates Motel', 'Amerique', '1');

-- 21 : BLACK MIRROR

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Black Mirror', 'D''après Charlie Brooker, chaque épisode a un casting, un décor et une réalité différente, mais ils traitent de la façon dont nous vivons maintenant et de la façon dont nous pourrions vivre dans dix minutes si nous commettions une erreur3.', '5', '22', '60', 'Netflix', 'https://www.youtube.com/embed/nSDviEdvw4U', 'blackMirror.jpg', 'Black Mirror', 'Black Mirror', 'Anglais', '1');

-- 22 : ESPRITS CRIMINELS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Esprits Criminels', 'L''équipe des profilers étudie les comportements et les esprits torturés des criminels les plus dangereux du pays, afin d''anticiper les crimes d''un éventuel tueur. Chaque membre de cette unité d''élite a sa personnalité, son histoire mais aussi sa spécialité, Ils sont tous dépendants les uns des autres et les résultats dépendent aussi de cette complémentarité.', '14', '314', '40', 'CBS', 'https://www.youtube.com/embed/t8eU2xOT9vk', 'criminalMinds.jpg', 'Esprits Criminels', 'Criminal Minds', 'Amerique', '1');

-- 23 : DEXTER

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Dexter', 'Brillant expert scientifique du service médico-légal de la police de Miami, Dexter Morgan est spécialisé dans l''analyse de prélèvements sanguins. Mais voilà, Dexter cache un terrible secret : il est également tueur en série. Un serial killer pas comme les autres, avec sa propre vision de la justice.', '8', '96', '45', 'Showtime', 'https://www.youtube.com/embed/YQeUmSD1c3g', 'dexter.jpg', 'Dexter', 'Dexter', 'Amerique', '1');

-- 24 : FRIENDS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Friends', 'Les péripéties de 6 jeunes New-Yorkais liés par une profonde amitié. Entre amour, travail, et famille, ils partagent leurs bonheurs et leurs soucis au Central Perk, leur café favori...', '10', '236', '22', 'NBC', 'https://www.youtube.com/embed/SHvzX2pl2ec', 'friends.jpg', 'Friends', 'Friends', 'Amerique', '1');

-- 25 : GOTHAM

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Gotham', 'Tout le monde connaît le Commissaire Gordon, adversaire redouté de la pègre de Gotham City, un homme dont la réputation rime avec la loi et l''ordre. Mais que sait-on de son histoire, de son ascension de policier débutant à commissaire ? Qu''est-ce que cela coûte de se frayer un chemin dans une ville régie secrètement par la corruption telle que Gotham City, terrain fertile des méchants les plus emblématiques ? Comment sont nés ces personnages hors du commun que sont Catwoman, le Pingouin, l''Homme-mystère, Double-Face et le Joker ?', '5', '100', '42', 'FOX', 'https://www.youtube.com/embed/lPe-oYBsbw0', 'gotham.jpg', 'Gotham', 'Gotham', 'Amerique', '1');

-- 26 : GRIMM

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Grimm', 'Des enquêtes policières, se déroulant dans un monde peuplé par des personnages des contes de Grimm, menées par Nick Burckhardt, un détective de Portland qui se met à voir certains êtres humains comme des animaux et qui est alors chargé d''une mission, celle de protéger les autres humains de ces créatures. Eddy Monroe, un ancien loup-garou reconverti qui tente de rester dans le droit chemin grâce à un savant mélange de médicaments, un régime et... des séances de fitness, lui prête main forte...', '6', '123', '42', 'NBC', 'https://www.youtube.com/embed/2rVy3RBJmNo', 'grimm.jpg', 'Grimm', 'Grimm', 'Amerique', '1');

-- 27 : HEROES

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Heroes', 'Partout dans le monde, un certain nombre d''individus en apparence ordinaires se révèlent dotés de capacités hors du commun : la régénération cellulaire, la téléportation, la télépathie... Ils ne savent pas ce qui leur arrive, ni les répercussions que tout cela pourrait avoir. Ils ignorent encore qu''ils font partie d''une évolution qui va changer le monde à jamais !', '4', '91', '40', 'NBC', 'https://www.youtube.com/embed/deNDnHW1sWo', 'heroes.jpg', 'Heroes', 'Heroes', 'Amerique', '1');

-- 28 : DR HOUSE

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Dr House', 'Le Dr Greg House est un médecin revêche qui ne fait confiance à personne, et encore moins à ses patients. Irrévérencieux et controversé, il n''en serait que plus heureux s''il pouvait ne pas adresser la parole à ses patients. Mais House est un brillant médecin. Et avec son équipe d''experts, il est prêt à tout pour résoudre les cas médicaux les plus mystérieux et sauver des vies.', '8', '177', '40', 'Fox', 'https://www.youtube.com/embed/MczMB8nU1sY', 'drHouse.jpg', 'Dr House', 'Dr House', 'Amerique', '1');

-- 29 : HOUSE OF CARDS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('House Of Cards', 'Suite à l''élection d''un nouveau président des États-Unis, le Tout-Washington attend la nomination de l''un de ses soutiens, le député Frank Underwood, à un poste majeur. Mais le président n''honore pas sa promesse. Blessé par ce coup bas qu''il n''a pas vu venir, Franck n''a plus qu''un but : la vengeance . En compagnie de sa femme Claire qui souhaite le voir arriver au sommet de l''État pour faciliter l''expansion de son association caritative, Underwood active ses réseaux et élabore en urgence une stratégie de reconquête tout-terrain.', '6', '73', '55', 'Netflix', 'https://www.youtube.com/embed/ULwUzF1q5w4', 'houseOfCards.jpg', 'House of Cards', 'House of Cards', 'Amerique', '1');

-- 30 : HOW I MEET YOUR MOTHER

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('How i meet your mother', 'Ted se remémore ses jeunes années, lorsqu''il était encore célibataire. Il revoit avec nostalgie ses moments d''égarements et de troubles, ses rencontres et ses recherches effrénées du Grand Amour.', '9', '208', '20', 'CBS', 'https://www.youtube.com/embed/aJtVL2_fA5w', 'hIMYM.jpg', 'How i meet your mother', 'How i meet your mother', 'Amerique', '1');

-- 31 : HOW TO GET AWAY WITH MURDER

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('How to get away with murder', 'La série raconte l''histoire d''Annalise Keating, professeure de droit pénal et avocate renommée à la tête de son propre cabinet à Philadelphie. Chaque année, quelques-uns de ses étudiants ont le privilège de travailler dans son cabinet. Mais un jour, ces derniers sont impliqués dans un meurtre…', '5', '75', '40', 'ABC', 'https://www.youtube.com/embed/8OfgUUtt9tM', 'hTGAWM.jpg', 'How to get away with murder', 'How to get away with murder', 'Amerique', '1');

-- 32 : LIE TO ME

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Lie to me', 'Le Dr Cal Lightman est un scientifique spécialisé dans la détection du mensonge. Qui que vous soyez, il sait si vous dites ou non la vérité... Véritable détecteur de mensonges fait homme, il sait décrypter sur un visage, dans une attitude ou au son d''une voix, la fausseté et le secret. Cette extraordinaire aptitude l''aide tout particulièrement dans les enquêtes criminelles qu''il résout au sein de son agence de détectives privés. Mais, dans sa vie privée, c''est une toute autre histoire...', '3', '48', '40', 'FOX', 'https://www.youtube.com/embed/pbOgHa34Ec8', 'lieToMe.jpg', 'Lie to me', 'Lie to me', 'Amerique', '1');

-- 33 : LOST

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('LOST', 'Après le crash de leur avion sur une île perdue, les survivants doivent apprendre à cohabiter et survivre dans cet environnement hostile. Bien vite, ils se rendent compte qu''une menace semble planer sur l''île...', '6', '121', '40', 'ABC', 'https://www.youtube.com/embed/KTu8iDynwNc', 'lost.jpg', 'Lost', 'Lost', 'Amerique', '1');

-- 34 : MALCOLM

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Malcolm', 'Petit génie malgré lui, Malcolm vit dans une famille hors du commun. Le jeune surdoué n''hésite pas à se servir de son intelligence pour faire les 400 coups avec ses frères : Francis, l''aîné, envoyé dans une école militaire après une bêtise de trop, Reese, une brute pas très maligne, et Dewey, le petit dernier, souffre douleur général. Les parents tentent tant bien que mal de canalyser l''énergie de ces petits démons. Si Loïs est despotique et veut tout contrôler, Hal, en revanche, est irresponsable et ne pense qu''à s''amuser.', '7', '151', '20', 'FOX', 'https://www.youtube.com/embed/PfID_33TL_A', 'malcolm.jpg', 'Malcolm', 'Malcolm', 'Amerique', '1');

-- 35 : DAREDEVIL

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Daredevil', 'Aveugle depuis ses neuf ans à la suite d''un accident, Matt Murdock développe une acuité extraordinaire lui permettant de combattre pour la justice le jour en tant qu''avocat. La nuit, il devient le super-héros Daredevil, justicier luttant contre l’injustice à New York, plus particulièrement dans le quartier de Hell''s Kitchen, corrompu par la criminalité depuis sa reconstruction après l''attaque des Chitauri et aux événements du film Avengers.', '3', '39', '45', 'Netflix', 'https://www.youtube.com/embed/jAy6NJ_D5vU', 'daredevil.jpg', 'Daredevil', 'Daredevil', 'Amerique', '1');

-- 36 : JESSICA JONES

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Jessica Jones', 'À trente ans, Jessica Jones, souffrant de stress post-traumatique suite à une confrontation avec l''Homme Pourpre, a remisé son costume de super-héroïne au placard afin d''ouvrir une agence de détective dans le but d''aider certains de ses confrères dotés de super-pouvoirs.', '3', '39', '45', 'Netflix', 'https://www.youtube.com/embed/nWHUjuJ8zxE', 'jessicaJones.jpg', 'Jessica Jones', 'Jessica Jones', 'Amerique', '1');

-- 37 : LUKE CAGE

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Luke Cage', 'Transformé en colosse surpuissant à la peau impénétrable après avoir été le cobaye d''une expérience sabotée, Luke Cage s''enfuit et tente de recommencer à zéro dans le Harlem d''aujourd''hui, à New York. Bientôt tiré de l''ombre, il va devoir se battre pour le cœur de sa ville dans un combat qui l''oblige à affronter un passé qu''il espérait avoir enterré.', '2', '26', '45', 'Netflix', 'https://www.youtube.com/embed/ORa4hPhGrpo', 'lukeCage.jpg', 'Luke Cage', 'Luke Cage', 'Amerique', '1');

-- 38 : THE PUNISHER

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Punisher', 'Après s’être vengé de ceux responsables de la mort de sa femme et de ses enfants, Frank Castle décèle un complot qui va bien plus loin que le milieu des criminels newyorkais. Désormais connu à travers toute la ville comme The Punisher, il doit découvrir la vérité sur les injustices qui l’entourent et touchent bien plus que sa seule famille.', '2', '26', '45', 'Netflix', 'https://www.youtube.com/embed/4QV6OZdmWY', 'thePunisher.jpg', 'The Punisher', 'The Punisher', 'Amerique', '1');

-- 39 : LA CASA DE PAPEL

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('La casa de papel', 'El Profesor est le cerveau d''un groupe de huit criminels dont l''ambition est de réaliser le braquage parfait : pourquoi attaquer une bijouterie ou une banque, quand on peut s''infiltrer dans l’antre des antres, l''usine de la Monnaie et des Timbres, et fabriquer son propre argent Pendant 11 jours, l''usine va ainsi être aux mains du groupe, avec 65 otages à l''intérieur. La guerre des nerfs avec les forces d''intervention commence alors...', '2', '30', '60', 'Netflix', 'https://www.youtube.com/embed/hMANIarjT50', 'laCasaDePapel.jpg', 'La casa de papel', 'La casa de Papel', 'Espagne', '1');

-- 40 : NARCOS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Narcos', 'Loin d’un simple biopic de Pablo Escobar, Narcos retrace la lutte acharnée des États-Unis et de la Colombie contre le cartel de la drogue de Medellín, l''organisation la plus lucrative et impitoyable de l''histoire criminelle moderne. En multipliant les points de vue — policier, politique, judiciaire et personnel — la série dépeint l’essor du trafic de cocaïne et le bras de fer sanglant engagé avec les narcotrafiquants qui contrôlent le marché avec violence et ingéniosité', '3', '30', '45', 'Netflix', 'https://www.youtube.com/embed/to9VYUGu1Ys', 'narcos.jpg', 'Narcos', 'Narcos', 'Amerique', '1');

-- 41 : PRETTY LITTLE LIARS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Pretty Little Liars', 'Après la disparition de leur leader Alison, une bande composée de quatre amies se désagrège. Un an plus tard, elles commencent à recevoir des messages d''un certain  A, qui les menace de dévoiler leurs secrets, y compris quelque chose dont seule Alison connaissait l’existence.', '7', '160', '40', 'ABC', 'https://www.youtube.com/embed/SUO8B47XtGY', 'prettyLittleLiars.jpg', 'Pretty Little Liars', 'Pretty Little Liars', 'Amerique', '1');

-- 42 : PRISON BREAK

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Prison Break', 'Michael Scofield s''engage dans une véritable lutte contre la montre : son frère Lincoln est dans le couloir de la mort, en attente de son exécution. Persuadé de son innocence mais à court de solutions, Michael décide de se faire incarcérer à son tour dans le pénitencier d''état de Fox River pour organiser leur évasion...', '5', '90', '40', 'FOX', 'https://www.youtube.com/embed/AL9zLctDJaU', 'prisonBreak.jpg', 'Prison Break', 'Prison Break', 'Amerique', '1');

-- 43 : REVENGE

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Revenge', 'Une jeune femme retourne vivre dans les Hamptons où elle a passé une partie de son enfance. Sous le pseudonyme d''Emily Thorne, elle a la ferme intention de détruire ceux qui ont brisé son innocence et gâché la vie de son père. Elle est prête à tout pour le venger...', '4', '89', '40', 'ABC', 'https://www.youtube.com/embed/VzWagiHW1PE', 'revenge.jpg', 'Revenge', 'Revenge', 'Amerique', '1');

-- 44 : SHERLOCK

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Sherlock', 'Les aventures modernisées du plus célèbre des enquêteurs : Sherlock Holmes et de son ami et assistant, le Dr Watson. Un remake vivant et drôle du classique de Arthur Conan Doyle revisité par Steven Moffat.', '4', '13', '90', 'BBC', 'https://www.youtube.com/embed/xK7S9mrFWL4', 'sherlock.jpg', 'Sherlock', 'Sherlock', 'Anglais', '1');

-- 45 : SUPERGIRL

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Supergirl', 'Kara Zor-El, cousine de Kal-El, est arrivée sur Terre, mais avec 30 ans de retard. Elle avait pour mission de protéger son cousin, mais celui-ci est devenu entre temps un super héros respecté de tous. La jeune fille est donc recueillie par une famille d''adoption, la famille Danvers. Grâce à eux, la jeune fille apprend à maîtriser ses pouvoirs, mais surtout à les cacher du grand public. Adulte, âgée de 24 ans, une catastrophe inattendue va l''obliger à se montrer telle qu''elle est vraiment aux yeux de tous. Très vite, les habitants de la ville ayant vu ses incroyables capacités, la surnomment Supergirl.', '4', '87', '40', 'The CW', 'https://www.youtube.com/embed/49RZx5tUKM4', 'supergirl.jpg', 'Supergirl', 'Supergirl', 'Amerique', '1');

-- 46 : STRANGER THINGS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Stranger Things', 'Quand un jeune garçon disparaît, une petite ville découvre une affaire mystérieuse, des expériences secrètes, des forces surnaturelles terrifiantes... et une fillette.', '2', '17', '50', 'Netflix', 'https://www.youtube.com/embed/Bb4uR9gTVXI', 'strangerThings.jpg', 'Stranger Things', 'Stranger Things', 'Amerique', '1');

-- 47 : TEEN WOLF

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Teen Wolf', 'Scott McCall est un adolescent tout ce qu''il y a de plus ordinaire. Il n''est pas le plus populaire de son lycée, il n''en est pas la risée non plus... Un soir, son meilleur ami Stiles le convainc de suivre en cachette les recherches de la police pour retrouver un corps dans les bois alentours. Au cours de cette expédition, il se retrouve nez à nez avec une bête étrange et particulièrement féroce. Il réchappe de peu à cette attaque et, chanceux, avec une seule blessure: une vilaine morsure. Le lendemain, Scott se sent bizarre. Sans qu''il le sache encore, sa vie vient de changer. Il est devenu un loup-garou...', '6', '100', '40', 'MTV', 'https://www.youtube.com/embed/1rCYDbefnmA', 'teenWolf.jpg', 'Teen Wolf', 'Teen Wolf', 'Amerique', '1');

-- 48 : THE MENTALIST

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Mentalist', 'The Mentalist raconte l''histoire de Patrick Jane, employé comme consultant indépendant pour le Bureau d''Investigation de Californie (CBI). Auparavant, il gagnait sa vie en tant que médium et assistait la police sur certaines affaires mais sa vie bascula lorsqu''il perdit les deux personnes les plus chères de sa vie en aidant la police à retrouver un tueur en série. Il utilise maintenant ses extraordinaires dons d''observation pour aider le CBI.', '7', '151', '40', 'CBS', 'https://www.youtube.com/embed/nn2Q69pSC_M', 'theMentalist.jpg', 'The Mentalist', 'The Mentalist', 'Amerique', '1');

-- 49 : VIKINGS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Vikings', 'Les exploits d''un groupe de vikings de la fin du 8ème siècle jusqu''au milieu du 11ème, mené par Ragnar Lodbrok, l''un des plus populaires héros viking de tous les temps, qui a régné quelques temps sur le Danemark et la Suède...', '5', '69', '45', 'History', 'https://www.youtube.com/embed/5av6OqFwz0', 'viking.jpg', 'Vikings', 'Vikings', 'Canada / Irlande', '1');

-- 50 : SONS OF ANARCHY

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Sons Of Anarchy', 'Afin de protéger leur ville des dealers et des entrepreneurs locaux, les membres d''un club de motos sont prêts à tout. Dans ce contexte critique, Jax Teller est partagé entre l''amour qu''il porte à sa confrérie et l''appréhension grandissante qu''il nourrit en voyant l''anarchie et le banditisme qui règne dans son club...', '7', '92', '45', 'FX', 'https://www.youtube.com/embed/ia4cggzpqYQ', 'sonsOfAnarchy.jpg', 'Sons Of Anarchy', 'Sons Of Anarchy', 'Amerique', '1');

-- 51 : BETTER CALL SAUL

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Better Call Saul', 'Six ans avant de croiser le chemin de Walter White, Saul Goodman, connu sous le nom de Jimmy McGill, est un avocat qui peine à joindre les deux bouts, à Albuquerque, au Nouveau-Mexique. Pour boucler ses fins de mois, il n''aura d''autres choix que se livrer à quelques petites escroqueries. Chemin faisant, il va faire des rencontres qui vont se révéler déterminantes dans son parcours : Nacho Varga, ou encore Mike Ehrmantraut, un criminel spécialisé dans le "nettoyage", qui deviendra son futur homme de main.', '4', '40', '45', 'Netflix', 'https://www.youtube.com/embed/9q4qzYrHVmI', 'betterCallSaul.jpg', 'Better Call Saul', 'Better Call Saul', 'Amerique', '1');

-- 52 : CHARMED

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Charmed', 'Prue et Piper sont toutes les deux sœurs et vivent ensemble dans le manoir familial à San Francisco. Le retour de Phoebe, leur sœur cadette, va bouleverser leur vie jusque là tranquille et paisible. Un soir d’orage, Phoebe, monte au grenier et est intriguée lorsqu''elle voit un rai de lumière dirigé vers un livre posé sur un socle. Elle s’en approche, ouvre le livre et lit la première page. Oyez maintenant les paroles des sorcières Les secrets sont cachés dans la nuit Les dieux anciens sont invoqués ici Afin que soit révélé l’art de la magie En cette nuit et en cette heure J''invoque le pouvoir supérieur Transmettez vos pouvoirs aux sœurs qui sont trois Nous voulons le pouvoir Donnez-nous le pouvoir. Le pouvoir des 3 est révélé et une nouvelle vie commence pour les 3 sœurs…', '8', '178', '42', 'The WB', 'https://www.youtube.com/embed/cdI43FwKKvg', 'charmed.jpg', 'Charmed', 'Charmed', 'Amerique', '1');

-- 53 : HANNIBAL

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Hannibal', 'La relation étrange entre le célèbre psychiatre Hannibal Lecter et l''un de ses patients, un jeune profiler du FBI nommé Will Graham, torturé par sa fascination dévorante pour les serial killers...', '3', '39', '40', 'NBC', 'https://www.youtube.com/embed/RuiklpUQ-p4', 'hannibal.jpg', 'Hannibal', 'Hannibal', 'Amerique', '1');

-- 54 : MR ROBOT

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Mr. Robot', 'Elliot est un jeune programmeur anti-social qui souffre d''un trouble du comportement et de dépression chronique. Il est ingénieur en cyber-sécurité le jour et hacker justicier la nuit. Elliot doit faire un choix lorsque le mystérieux chef d''un groupe underground de hackers le recrute pour détruire la société qu''il est payé pour protéger. Contraint par ses convictions personnelles, Elliot a du mal à résister à la chance de détruire les PDG''s de multinationales qui, selon lui, dirigent (et ruinent) le monde.', '3', '32', '40', 'USA Network', 'https://www.youtube.com/embed/xIBiJ_SzJTA', 'mrRobot.jpg', 'Mr. Robot', 'Mr. Robot', 'Amerique', '1');

-- 55 : NIP/TUCK

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Nip/Tuck', 'Deux médecins spécialisés dans la chirurgie esthétique jonglent entre leurs patients de la clinique privée de Miami dans laquelle ils travaillent et leur vie privée mouvementée.', '6', '100', '45', 'FX', 'https://www.youtube.com/embed/J5j7aSh0UUQ', 'nipTuck.jpg', 'Nip/Tuck', 'Nip/Tuck', 'Amerique', '1');

-- 56 : SCREAM

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Scream', 'À Lakewood, un tueur masqué déguisé en fantôme sème la terreur autour de lui, faisant remonter à la surface les secrets d''un passé trouble. Le coupable aurait-il un lien avec le mythique Brandon James, qui avait à l''époque laissé de nombreuses victimes sur son passage ? L''assassin était alors obsédé par la jeune et belle Daisy. La fille de celle-ci, Emma, a aujourd''hui l''âge de sa mère au moment des drames. Le cauchemar recommencerait-il ? Qui sera la prochaine cible du détraqué ?', '2', '24', '40', 'MTV', 'https://www.youtube.com/embed/0YiOtdDnwJs', 'scream.jpg', 'Scream', 'Scream', 'Amerique', '1');

-- 57 : SHADOWHUNTERS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Shadowhunters', 'Clarissa Fray est une jeune adulte de 18 ans qui vit à New York avec sa mère et étudie l''art. Lors d''une soirée dans un club new-yorkais, elle assiste au meurtre d''une femme par trois jeunes étranges qu''elle seule semble voir et tue par accident un homme. De retour chez elle, sa mère, Jocelyn, lui révèle leurs véritables nature : elles descendent d''une longue lignée de Chasseurs d''Ombres. Mais avant de pouvoir lui en dire plus, des hommes viennent les attaquer, ce qui pousse Jocelyn à téléporter Clary ailleurs. Clary fait alors la rencontre de Jace, l''un des jeunes du club mais surtout un Chasseur d''Ombres. Au côté d''autres Chasseurs d''Ombres, il lui fait découvrir l''Institut ainsi qu''un monde surprenant et peuplé de Créatures Obscures telles que les vampires, les loups-garous et autres démons. Clary va tenter de comprendre ce monde particulier auquel elle appartient depuis toujours sans le savoir et de sauver sa mère.', '3', '55', '40', 'FreeForm', 'https://www.youtube.com/embed/nA6nGwUwLt4', 'shadowhunters.jpg', 'Shadowhunters', 'Shadowhunters', 'Amerique', '1');

-- 58 : SPARTACUS

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('Spartacus', 'Bien avant l’arrivée de Spartacus, la cité de Capoue se prépare à inaugurer une nouvelle arène gigantesque. Y faire combattre ses gladiateurs serait un honneur et une source de richesse pour tous les propriétaires de combattants de la région. Le jeune Batiatus fait partie de ceux-là, mais il ne fait que gérer l’affaire familiale en l’absence de son père. Il va pourtant user de tous les stratagèmes pour imposer ses gladiateurs, quitte à sombrer avec sa femme, Lucrétia, dans les excès les plus abjects…', '4', '39', '40', 'Starz', 'https://www.youtube.com/embed/eJiBouML3FQ', 'spartacus.jpg', 'Spartacus', 'Spartacus', 'Amerique', '1');

-- 59 : THE FOLLOWING

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Following', 'Joe Carroll, un serial killer diabolique, utilise la technologie pour créer une secte de tueurs en séries, tous reliés les uns aux autres alors qu''ils sont dispersés aux quatre coins des Etats-Unis. L''ancien agent du FBI Ryan Hardy, qui l''a traqué et capturé par le passé, qui a même écrit un livre sur lui et qui connait la moindre de ses ruses, se voit contraint de reprendre du service...', '3', '45', '40', 'FOX', 'https://www.youtube.com/embed/EbcCVzRxzjU', 'theFollowing.jpg', 'The Following', 'The Following', 'Amerique', '1');

-- 60 : THE HAUNTING OF HILL HOUSE

INSERT INTO `sp_series_pages`(`sp_series_pages_title`, `sp_series_pages_description`, `sp_series_pages_number_seasons`, `sp_series_pages_number_episodes`, `sp_series_pages_duration_episodes`, `sp_series_pages_diffusion_channel`, `sp_series_pages_trailer`, `sp_series_pages_image`, `sp_series_pages_french_title`, `sp_series_pages_original_title`, `sp_series_pages_origin`, `sp_series_pages_verification`) VALUES('The Haunting', 'Plusieurs frères et sœurs qui, enfants, ont grandi dans la demeure qui allait devenir la maison hantée la plus célèbre des États-Unis, sont contraints de se réunir pour finalement affronter les fantômes de leur passé, dont certains sont encore bien présents dans leurs esprits alors que d’autres continuent de hanter la fameuse Hill House.', '1', '10', '40', 'Netflix', 'https://www.youtube.com/embed/G9OzG53VwIk', 'theHaunting.jpg', 'The Haunting', 'The Haunting', 'Amerique', '1');